export const FETCHED_DATA_SUCCESS = 'FETCHED_DATA_SUCCESS';
export const CALCULATED_ROWS_FINISHED = 'CALCULATED_ROWS_FINISHED';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const SORT_COLUMN_AND_DIRECTION_UPDATED = 'SORT_COLUMN_AND_DIRECTION_UPDATED';
export const ROW_ORDER_CHANGED = 'ROW_ORDER_CHANGED';
